# Generated by Django 5.2.6 on 2025-09-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exam_results', to='exams.question'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершен'), ('time_expired', 'Время вышло')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='attempt_number',
        ),
    ]
